name: cannacal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.7.12"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^2.3.1
  google_mobile_ads: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/onboard.png"