name: cannacal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.1.9
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  google_mobile_ads: ^1.2.0
  hive: 2.1.0
  hive_flutter: 1.1.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  build_runner: 2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/onboard.png"